sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '8'
script:
  - yarn lint
  - yarn test
  - yarn report-coverage
  - yarn coveralls
  - yarn build:production
  - yarn test:lib
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
